name: tests
on: [push, pull_request]
jobs:
  ctest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TYPE: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      run: sudo docker build -t tests --build-arg build_type=${{ matrix.BUILD_TYPE }} .
    - name: run tests
      run: sudo docker run tests
  macOS:
    runs-on: macOS-10.15
    strategy:
      matrix:
        BUILD_TYPE: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
        brew install python sqlite zstd samtools aria2
        /usr/local/bin/pip3 install pytest pytest-xdist
        # test web_vfs using the older system libcurl
        brew uninstall --ignore-dependencies curl
        curl --version
        which curl
        otool -L $(which curl)
        # smoke test
        samtools view -O BAM -@ 4 -o chr21:20000000-25000000.bam https://s3.amazonaws.com/1000genomes/1000G_2504_high_coverage/data/ERR3239334/NA12878.final.cram chr21:20000000-25000000
    - name: build
      run: |
        CXXFLAGS="-I$(brew --prefix)/include -I$(brew --prefix)/opt/sqlite/include" \
        LDFLAGS="-L$(brew --prefix)/lib -L$(brew --prefix)/opt/sqlite/lib" \
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} \
                -DCMAKE_PREFIX_PATH=$(brew --prefix)/opt/sqlite \
                -B build .
        cmake --build build -j 4
    - name: ctest
      run: |
        export PREFIX=$(brew --prefix)
        export PATH=$(ls -p1 ${PREFIX}/opt/python@*)/bin:${PREFIX}/opt/sqlite/bin:$PATH
        cd build
        ctest -V
